### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by uzias10** [SistemasTecTlaxiaco/infografia-de-hilos-uzias10#2]
[Hilos en c#.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-uzias10/files/6462488/Hilos.en.c.pdf)

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 18/20

**Comment by Rigoberto2001** [comment]
CALIFICACIÓN: 18/20.

CALIFICÓ: RIGOBERTO RAMIREZ NICOLÁS

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado..
